---
- name: Install and Configure Apache on Port 8081
  hosts: node_server
  become: yes
  tasks:
    - name: Ensure Apache is installed
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Change Apache listening port to 8081
      lineinfile:
        path: /etc/apache2/ports.conf
        regexp: '^Listen 80'
        line: 'Listen 8081'

    - name: Update default VirtualHost to port 8081
      lineinfile:
        path: /etc/apache2/sites-available/000-default.conf
        regexp: '<VirtualHost \*:80>'
        line: '<VirtualHost *:8081>'

    - name: Ensure Apache is started and enabled
      service:
        name: apache2
        state: restarted
        enabled: yes
