- name: Deploy Custom Website to Node Server
  hosts: all
  become: true
  tasks:
    - name: Ensure Project Directory exists
      file:
        path: /home/star/app
        state: directory

    - name: Copy index.html and Dockerfile to Node
      copy:
        src: "{{ item }}"
        dest: /home/star/app/
      with_items:
        - index.html
        - Dockerfile

    - name: Build and Restart Docker Container
      shell: |
        cd /home/star/app
        docker build -t myapp:latest .
        docker rm -f myappcontainer || true
        docker run -d --name myappcontainer -p 80:80 myapp:latest
