---
- name: Setup Apache as Reverse Proxy
  hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: Install Apache2
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Enable Proxy Modules
      shell: a2enmod proxy proxy_http
      notify: Restart Apache

    - name: Configure Reverse Proxy to Port 9000
      copy:
        dest: /etc/apache2/sites-available/000-default.conf
        content: |
          <VirtualHost *:80>
              ProxyPreserveHost On
              ProxyPass / http://127.0.0.1:9000/
              ProxyPassReverse / http://127.0.0.1:9000/
          </VirtualHost>

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
