---
- name: Install and Configure Apache
  hosts: web
  become: yes  # This is critical - it allows sudo
  tasks:
    - name: Force Install Apache
      apt:
        name: apache2
        state: latest
        update_cache: yes

    - name: Set Port to 8081 in ports.conf
      copy:
        content: "Listen 8081"
        dest: /etc/apache2/ports.conf

    - name: Update VirtualHost to 8081
      lineinfile:
        path: /etc/apache2/sites-available/000-default.conf
        regexp: '<VirtualHost \*:80>'
        line: '<VirtualHost *:8081>'

    - name: Restart and Enable Apache
      service:
        name: apache2
        state: restarted
        enabled: yes
