---
- name: Install Monitoring Stack
  hosts: all
  become: yes
  tasks:
    - name: Create Prometheus config directory
      file:
        path: /etc/prometheus
        state: directory

    - name: Configure Prometheus to scrape metrics
      copy:
        dest: /etc/prometheus/prometheus.yml
        content: |
          global:
            scrape_interval: 15s
          scrape_configs:
            - job_name: 'node_exporter'
              static_configs:
                - targets: ['localhost:9100']
            - job_name: 'docker_containers'
              static_configs:
                - targets: ['localhost:9323'] # Optional: Docker Engine metrics

    - name: Run Node Exporter container
      docker_container:
        name: node_exporter
        image: prom/node-exporter:latest
        state: started
        restart_policy: always
        ports:
          - "9100:9100"

    - name: Run Prometheus container
      docker_container:
        name: prometheus
        image: prom/prometheus:latest
        state: started
        restart_policy: always
        volumes:
          - /etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        ports:
          - "9090:9090"

    - name: Run Grafana container
      docker_container:
        name: grafana
        image: grafana/grafana:latest
        state: started
        restart_policy: always
        ports:
          - "3000:3000"
